### ISSUE TITLE
Line width setting in constants does not work

### ISSUE THREAD

**Issue by mrtomeq** [KensoBI/spc-histogram#4]
![spc-histogram-line-width](https://github.com/KensoBI/spc-histogram/assets/8570009/f6dc4f59-934b-43c0-a045-fd5057d411f5)

https://dev.kensobi.com/d/da34e033-6123-4973-9b03-0a3326fe8d6f/spc-histograms?orgId=1&var-characteristicid=6&showCategory=Panel%20options&editPanel=6

**Comment by mrGnowak** [comment]
commit [c98876f](https://github.com/KensoBI/spc-histogram/pull/6/commits/c98876f6f70cbf3703e07ca0df05d9dba0ee5331)

**Comment by mrtomeq** [comment]
LGTM, thanks!
