### ISSUE TITLE
Would it be possible to add scaling to the Y-axis

### ISSUE THREAD

**Issue by DrAndersBjork** [KensoBI/spc-histogram#8]
Would it be possible for you to add a setting for scaling to the Y-axis so the sum of events/datapoints gets to be 0-100%?

**Comment by mrtomeq** [comment]
Hi @DrAndersBjork! Are you asking for stacking to 100 of multiple series (feature available in native Grafana histogram)? If not, can you provide a sample image of a chart you are trying to build?

![image](https://github.com/user-attachments/assets/1a2f8390-3b95-48af-a344-076952a63d06)
